stages:
  - sync

variables:
  GIT_DEPTH: 0 # Ensure full clone for mirroring

sync_to_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.name "Aman Devani"
    - git config --global user.email "amandevani25@gmail.com"
  script:
    - git remote add github "https://${GITHUB_TOKEN}@github.com/AmanDevani/aman-portfolio-nextjs-web.git"
    - git push --mirror github
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  only:
    - branches
    - merge_requests
