stages:
  - sync

sync_with_github:
  stage: sync
  before_script:
    - git config --global user.email "amandevani25@gmail.com"
    - git config --global user.name "Aman Devani"
    - git remote -v # Check existing remotes
  script:
    - echo "Syncing branch $CI_COMMIT_REF_NAME to GitHub"
    - git fetch --all
    - git checkout -B "$CI_COMMIT_REF_NAME" "origin/$CI_COMMIT_REF_NAME"
    - git remote remove github || true # Remove remote if it exists
    - git remote add github "https://${GITHUB_TOKEN}@github.com/AmanDevani/aman-portfolio-nextjs-web.git"
    - git push --force github "$CI_COMMIT_REF_NAME:$CI_COMMIT_REF_NAME"
  only:
    - branches
    - merge_requests
  variables:
    GIT_DEPTH: 0
