stages:
  - sync

sync_with_github:
  stage: sync
  before_script:
    - git config --global user.email "amandevani25@gmail.com"
    - git config --global user.name "Aman Devani"
    - git remote -v # Debug: Check existing remotes
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
    - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/AmanDevani/aman-portfolio-nextjs-web.git"
    - git push origin "$CI_COMMIT_BRANCH"
  only:
    - branches
    - merge_requests
  variables:
    GIT_DEPTH: 0
