stages:
  - sync

sync_with_github:
  stage: sync
  script:
    - |
      echo "Syncing branch $CI_COMMIT_REF_NAME to GitHub"
      git fetch origin
      git checkout -B "$CI_COMMIT_REF_NAME" "origin/$CI_COMMIT_REF_NAME"
      echo "Checked out branch: $(git branch --show-current)"
    git remote add github "https://${GITHUB_TOKEN}@github.com/AmanDevani/aman-portfolio-nextjs-web.git"
      git push github "$CI_COMMIT_REF_NAME:$CI_COMMIT_REF_NAME"
  only:
    - branches
    - merge_requests
  variables:
    GIT_DEPTH: 0
